stages:
  data_ingestion:
    cmd: python src/components/data_ingestion.py
    deps:
      - src/components/data_ingestion.py
      - data/raw/loan.csv
      - params.yaml
    outs:
      - data/interim/cleaned.csv