data_ingestion:
  raw_data_path: data/raw/loan_default.csv
  clean_data_path: data/interim/cleaned.csv

data_preprocessing:
  input_data_path: data/interim/cleaned.csv
  processed_data_path: data/processed/processed.csv
  encoder_path: src/artifacts/encoder.pkl

model_training:
  input_data_path: data/processed/processed.csv
  model_path: models/model.pkl
  scaler_path: src/artifacts/scaler.pkl

  test_size: 0.3
  random_state: 42

  model_params:
    C: 0.10728990079492859
    penalty: l1
    solver: liblinear
    max_iter: 1000    